server:
  port: 8095
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/depositos_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:  
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    root: INFO
    com.backend.microservices: WARN
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: logs/depositos-microservice.log
    max-size: 10MB
    max-history: 30